### PR TITLE
basic edits

### PR DESCRIPTION
**Pull request by ksathyareddy7**
The `npm build` command should not have been mentioned here.

### CODE REVIEW

**Comment by Hyperclaw79** [comment]
No, this is the local deployment section. The dev would want to test the production stage of the app too. So, `npm build` is desirable.

**Comment by ksathyareddy7** [comment]
you mean to say that we can make changes in the build version directly and view it ?

**Comment by Hyperclaw79** [comment]
No.
The local deployment is not just about live reload. We need to even see the
optimized version of the app. That's what `build` is useful for.

**Comment by ksathyareddy7** [comment]
yup i agree with you but both the commands, one for local dev and live reloading , two to create a build version of the app in same line is quite confusing. Check the new patch commit.

**Pull request closed without merging**
